/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.labs;

import java.awt.event.ActionEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author bridj
 */
public class LibraryView extends javax.swing.JFrame implements LibraryObserver {
    private LibraryController libraryController;
    private LibraryModel model;
    private ResourceBundle messages;
    Connection connection = null;

    public LibraryView() {
        Locale locale = new Locale("en", "US"); // Default or from user's preference
        loadResourceBundle(locale);
        initComponents();
        setupActionListeners();
        updateTexts();
        makeDBConnection();
    }

    private void loadResourceBundle(Locale locale) {
        messages = ResourceBundle.getBundle("resources.MessagesBundle", locale);
    }

    public void changeLocale(Locale newLocale) {
        messages = ResourceBundle.getBundle("resources.MessagesBundle", newLocale);
        updateTexts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibraryFrame = new javax.swing.JFrame();
        languageGroup = new javax.swing.ButtonGroup();
        libraryPane = new javax.swing.JTabbedPane();
        libraryPanel = new javax.swing.JPanel();
        booksTitleLabel = new javax.swing.JLabel();
        titleLibraryLabel = new javax.swing.JLabel();
        authorLibraryLabel = new javax.swing.JLabel();
        yearLibraryLabel = new javax.swing.JLabel();
        idLibraryLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        addBookButton = new javax.swing.JButton();
        removeBookButton = new javax.swing.JButton();
        searchBookButton = new javax.swing.JButton();
        clearSearchButton = new javax.swing.JButton();
        bookDisplayAreaScrollPane = new javax.swing.JScrollPane();
        bookDisplayArea = new javax.swing.JTextArea();
        languageSelectionPanel = new javax.swing.JPanel();
        englishRadioButton = new javax.swing.JRadioButton();
        frenchRadioButton = new javax.swing.JRadioButton();

        javax.swing.GroupLayout LibraryFrameLayout = new javax.swing.GroupLayout(LibraryFrame.getContentPane());
        LibraryFrame.getContentPane().setLayout(LibraryFrameLayout);
        LibraryFrameLayout.setHorizontalGroup(
            LibraryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        LibraryFrameLayout.setVerticalGroup(
            LibraryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        languageGroup.add(englishRadioButton);
        languageGroup.add(frenchRadioButton);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Frame");
        setName("libraryFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        libraryPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        libraryPane.setName("tabPane1"); // NOI18N

        libraryPanel.setName("libraryTabPane"); // NOI18N

        booksTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        booksTitleLabel.setText("Books");

        titleLibraryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleLibraryLabel.setText("Title");

        authorLibraryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        authorLibraryLabel.setText("Author");

        yearLibraryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLibraryLabel.setText("Year");

        idLibraryLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idLibraryLabel.setText("ID");

        addBookButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBookButton.setText("Add Book");
        addBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookButtonMouseClicked(evt);
            }
        });
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        removeBookButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeBookButton.setText("Remove Book");
        removeBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBookButtonMouseClicked(evt);
            }
        });

        searchBookButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBookButton.setText("Search Book");
        searchBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBookButtonMouseClicked(evt);
            }
        });

        clearSearchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearSearchButton.setText("Clear Search");
        clearSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearSearchButtonMouseClicked(evt);
            }
        });

        bookDisplayArea.setColumns(20);
        bookDisplayArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookDisplayArea.setRows(5);
        bookDisplayAreaScrollPane.setViewportView(bookDisplayArea);

        englishRadioButton.setText("English");
        englishRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                englishRadioButtonMouseClicked(evt);
            }
        });

        frenchRadioButton.setText("French");
        frenchRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frenchRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout languageSelectionPanelLayout = new javax.swing.GroupLayout(languageSelectionPanel);
        languageSelectionPanel.setLayout(languageSelectionPanelLayout);
        languageSelectionPanelLayout.setHorizontalGroup(
            languageSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languageSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languageSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(englishRadioButton)
                    .addComponent(frenchRadioButton))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        languageSelectionPanelLayout.setVerticalGroup(
            languageSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, languageSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(englishRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frenchRadioButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout libraryPanelLayout = new javax.swing.GroupLayout(libraryPanel);
        libraryPanel.setLayout(libraryPanelLayout);
        libraryPanelLayout.setHorizontalGroup(
            libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryPanelLayout.createSequentialGroup()
                .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(libraryPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bookDisplayAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(libraryPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(languageSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booksTitleLabel)))
                .addGap(18, 18, 18)
                .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(searchBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libraryPanelLayout.createSequentialGroup()
                            .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titleLibraryLabel)
                                .addComponent(authorLibraryLabel)
                                .addComponent(yearLibraryLabel)
                                .addComponent(idLibraryLabel))
                            .addGap(20, 20, 20)
                            .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(authorTextField)
                                .addComponent(yearTextField)
                                .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(titleTextField))))
                    .addComponent(clearSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBookButton)
                    .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        libraryPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBookButton, authorTextField, clearSearchButton, idTextField, removeBookButton, searchBookButton, titleTextField, yearTextField});

        libraryPanelLayout.setVerticalGroup(
            libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libraryPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLibraryLabel)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(booksTitleLabel))
                    .addComponent(languageSelectionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(libraryPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLibraryLabel)
                            .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLibraryLabel)
                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLibraryLabel)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addBookButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchBookButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeBookButton))
                    .addGroup(libraryPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bookDisplayAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        libraryPane.addTab("Library", libraryPanel);

        getContentPane().add(libraryPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frenchRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frenchRadioButtonMouseClicked

    }//GEN-LAST:event_frenchRadioButtonMouseClicked

    private void englishRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_englishRadioButtonMouseClicked

    }//GEN-LAST:event_englishRadioButtonMouseClicked

    private void clearSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearSearchButtonMouseClicked

    }//GEN-LAST:event_clearSearchButtonMouseClicked

    private void searchBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBookButtonMouseClicked

    }//GEN-LAST:event_searchBookButtonMouseClicked

    private void removeBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBookButtonMouseClicked

    }//GEN-LAST:event_removeBookButtonMouseClicked

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed

    }//GEN-LAST:event_addBookButtonActionPerformed

    private void addBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookButtonMouseClicked

    }//GEN-LAST:event_addBookButtonMouseClicked

    private void setupActionListeners() {
        englishRadioButton.addActionListener(e -> changeLocale(new Locale("en", "US")));
        frenchRadioButton.addActionListener(e -> changeLocale(new Locale("fr", "FR")));
    }

    private void updateTexts() {
        titleLibraryLabel.setText(messages.getString("Title"));
        authorLibraryLabel.setText(messages.getString("Author"));
        yearLibraryLabel.setText(messages.getString("Year"));
        idLibraryLabel.setText(messages.getString("ID"));
        addBookButton.setText(messages.getString("AddBook"));
        removeBookButton.setText(messages.getString("RemoveBook"));
        searchBookButton.setText(messages.getString("SearchBook"));
        clearSearchButton.setText(messages.getString("ClearSearch"));
        booksTitleLabel.setText(messages.getString("Books"));
        this.invalidate();
        this.validate();
        this.repaint();
    }

    private ResultSet makeDBConnection() {
        try {
            connection = DriverManager.getConnection("jdbc:sqlite:sample.db");
            Statement statement = connection.createStatement();
            statement.setQueryTimeout(30);

            statement.executeUpdate("drop table if exists book");
            statement.executeUpdate("create table book (title string, author string)");
            statement.executeUpdate("insert into book values('little women', 'louisa may alcott')");
            statement.executeUpdate("insert into book values('crime and punishment', 'fyodor dostoyevsky')");
            ResultSet rs = statement.executeQuery("select * from person");
            return rs;

        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        return null;
    }
   
    @Override
    public void update() {
        //
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame LibraryFrame;
    private javax.swing.JButton addBookButton;
    private javax.swing.JLabel authorLibraryLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JTextArea bookDisplayArea;
    private javax.swing.JScrollPane bookDisplayAreaScrollPane;
    private javax.swing.JLabel booksTitleLabel;
    private javax.swing.JButton clearSearchButton;
    private javax.swing.JRadioButton englishRadioButton;
    private javax.swing.JRadioButton frenchRadioButton;
    private javax.swing.JLabel idLibraryLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.ButtonGroup languageGroup;
    private javax.swing.JPanel languageSelectionPanel;
    private javax.swing.JTabbedPane libraryPane;
    private javax.swing.JPanel libraryPanel;
    private javax.swing.JButton removeBookButton;
    private javax.swing.JButton searchBookButton;
    private javax.swing.JLabel titleLibraryLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel yearLibraryLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables

  
}
